### PR TITLE
Add missing jshint as a dependency

### PR DESCRIPTION
**Pull request by MiquelAdell**
Gulp was complaining of missing jshint.

I think that solves it.

### CODE REVIEW

**Comment by MiquelAdell** [comment]
@synapticism I'm not sure if you where using features or just develop/master so I pushed directly onto develop.

I'm not very used on pull requests so please let me know if something is wrong.

Thanks!

**Comment by synapticism** [comment]
I think there's a bit of a wrinkle here since it's advisable to install jshint globally... I'll take another look at this soon, thanks!

**Comment by felixfischer** [comment]
👍

**Comment by xsynaptic** [comment]
What do you think about moving from JSHint to ESLint as a default? I've got an example integration on the develop branch at present: https://github.com/synapticism/wordpress-gulp-starter-kit/tree/develop

**Comment by xsynaptic** [comment]
OK, moving forward I'm going all-in on ESLint. Thank you for the PR, future changes will be going in a different direction though.

**Pull request closed without merging**
